name: upload-javadoc

on:
  push:
    tags:
      - 'acra-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Checkout acra
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: 'main'
          persist-credentials: false
          fetch-depth: 0
      - name: Checkout github pages
        uses: actions/checkout@v2
        with:
          repository: 'ACRA/acra.github.com'
          path: 'web'
          persist-credentials: false
          fetch-depth: 0
      - name: Generate Javadoc
        run: ./gradlew dokkaHtmlCollector --no-daemon
        working-directory: ./main
      - name: Extract version
        id: version
        run: echo "::set-output name=value::$(git describe --abbrev=0 | sed -e "s/^acra-//")"
        working-directory: ./main
      - name: Update Javadoc
        run: |
          mkdir ./web/javadoc/${{ steps.version.outputs.value }}
          cp -a ./main/build/dokka/htmlCollector/. ./web/javadoc/${{ steps.version.outputs.value }}/
          echo  "- [${{ steps.version.outputs.value }}](${{ steps.version.outputs.value }}/acra)" >> ./web/javadoc/index.md
          ln -sfn "${{ steps.version.outputs.value }}/" ./web/javadoc/latest
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add javadoc for version ${{ steps.version.outputs.value }}"
        working-directory: ./web
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          repository: 'ACRA/acra.github.com'
          branch: 'master'
          directory: ./web
