name: upload-javadoc

on:
  push:
    tags:
      - 'acra-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '1.8'
      - name: Checkout acra
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Generate Javadoc
        run: ./gradlew assembleRelease dokkaHtmlCollector --no-daemon
      - name: Extract version
        id: version
        run: echo "::set-output name=value::$(git describe --abbrev=0 | sed -e "s/^acra-//")"
      - name: Update Javadoc
        run: |
          mkdir ./web/static/javadoc/${{ steps.version.outputs.value }}
          cp -a ./build/dokka/htmlCollector/. ./web/static/javadoc/${{ steps.version.outputs.value }}/
          ln -sfn "${{ steps.version.outputs.value }}/" ./web/static/javadoc/latest
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'web/static/javadoc'
          message: "Add javadoc for version ${{ steps.version.outputs.value }}"
          github_token: ${{ secrets.PUSH_TOKEN }}
          branch: 'master'
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
